//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOKtch
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeaderTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HeaderTransaction()
        {
            this.TransactionDetails = new HashSet<TransactionDetail>();
        }
    
        public int HeaderTransactionId { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string TransactionStatus { get; set; }
        public string MemberEmail { get; set; }
    
        public virtual Member Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionDetail> TransactionDetails { get; set; }
    }
}
